name: jose_mod
description: Modified The base JOSE Library.
version: 0.0.1
homepage: https://github.com/shinnthant-lib/jose

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  asn1lib: ^1.5.0
  collection: ^1.17.2
  crypto_keys: ^0.3.0+1
  http: ^1.1.0
  http_parser: ^4.0.2
  meta: ^1.9.1
  typed_data: ^1.3.2
  x509: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.3
  lints: ^2.1.1


